export { testIds }

let testIds = {
	auth: {
		dialog: "auth-dialog",
		initialCreateAccount: "auth-initial-create-account",
		initialSignIn: "auth-initial-sign-in",
		createPassphrase: "auth-create-passphrase",
		createCopy: "auth-create-copy",
		createReroll: "auth-create-reroll",
		createSubmit: "auth-create-submit",
		createBack: "auth-create-back",
		createError: "auth-create-error",
		loginPassphrase: "auth-login-passphrase",
		loginSubmit: "auth-login-submit",
		loginBack: "auth-login-back",
		loginError: "auth-login-error",
		settingsSignIn: "settings-sign-in",
		settingsSignOut: "settings-sign-out",
	},
	doc: {
		newButton: "doc-new-button",
		searchInput: "doc-search-input",
		fileMenuButton: "doc-file-menu-button",
		list: "doc-list",
		listItem: "doc-list-item",
		editor: "doc-editor",
		editorContent: "doc-editor-content",
		title: "doc-title",
		deleteButton: "doc-delete-button",
		duplicateButton: "doc-duplicate-button",
		shareButton: "doc-share-button",
		moveButton: "doc-move-button",
		exportButton: "doc-export-button",
		pinButton: "doc-pin-button",
		restoreButton: "doc-restore-button",
		permanentDeleteButton: "doc-permanent-delete-button",
	},
	editor: {
		toolbar: "editor-toolbar",
		formatBold: "editor-format-bold",
		formatItalic: "editor-format-italic",
		formatCode: "editor-format-code",
		formatLink: "editor-format-link",
		insertImage: "editor-insert-image",
		findButton: "editor-find-button",
		presentButton: "editor-present-button",
		previewButton: "editor-preview-button",
		timeMachineButton: "editor-time-machine-button",
	},
	sidebar: {
		left: "sidebar-left",
		right: "sidebar-right",
		syncStatus: "sidebar-sync-status",
		settingsButton: "sidebar-settings-button",
		importExport: "sidebar-import-export",
		spaceSelector: "sidebar-space-selector",
		documentList: "sidebar-document-list",
		assetsSection: "sidebar-assets-section",
		collaborationSection: "sidebar-collaboration-section",
	},
	dialog: {
		deleteConfirm: "dialog-delete-confirm",
		duplicate: "dialog-duplicate",
		share: "dialog-share",
		move: "dialog-move",
		export: "dialog-export",
		import: "dialog-import",
	},
	space: {
		selector: "space-selector",
		selectorTrigger: "space-selector-trigger",
		createButton: "space-create-button",
		createDialog: "space-create-dialog",
		createNameInput: "space-create-name-input",
		createSubmit: "space-create-submit",
		listItem: "space-list-item",
		inviteButton: "space-invite-button",
		settingsButton: "space-settings-button",
		leaveButton: "space-leave-button",
		shareDialog: "space-share-dialog",
		shareWriterInviteButton: "space-share-invite-writer",
		shareReaderInviteButton: "space-share-invite-reader",
		shareInviteLinkInput: "space-share-invite-link-input",
		sharePendingInviteRow: "space-share-pending-invite-row",
		sharePendingInviteRevoke: "space-share-pending-invite-revoke",
		settingsNameInput: "space-settings-name-input",
		dangerDeleteButton: "space-danger-delete-button",
		dangerDeleteNameInput: "space-danger-delete-name-input",
		dangerDeletePhraseInput: "space-danger-delete-phrase-input",
		dangerDeleteConfirmButton: "space-danger-delete-confirm-button",
	},
	collab: {
		docShareOpenButton: "doc-collab-open-share",
		docShareDialog: "doc-share-dialog",
		docShareInviteWriterButton: "doc-share-invite-writer",
		docShareInviteReaderButton: "doc-share-invite-reader",
		docShareInviteLinkInput: "doc-share-invite-link-input",
		docSharePendingInviteRow: "doc-share-pending-invite-row",
		docSharePendingInviteRevoke: "doc-share-pending-invite-revoke",
	},
	invite: {
		signInButton: "invite-sign-in-button",
		successState: "invite-success-state",
		errorState: "invite-error-state",
	},
	asset: {
		uploadButton: "asset-upload-button",
		list: "asset-list",
		listItem: "asset-list-item",
		deleteButton: "asset-delete-button",
		renameButton: "asset-rename-button",
		downloadButton: "asset-download-button",
	},
} as const
