/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewRouteImport } from './routes/new'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalIndexRouteImport } from './routes/local.index'
import { Route as TutorSlugRouteImport } from './routes/tutor.$slug'
import { Route as LocalPreviewRouteImport } from './routes/local.preview'
import { Route as SpacesSpaceIdIndexRouteImport } from './routes/spaces.$spaceId.index'
import { Route as DocIdIndexRouteImport } from './routes/doc.$id.index'
import { Route as SpacesSpaceIdSettingsRouteImport } from './routes/spaces.$spaceId.settings'
import { Route as DocIdTimemachineRouteImport } from './routes/doc.$id.timemachine'
import { Route as DocIdTeleprompterRouteImport } from './routes/doc.$id.teleprompter'
import { Route as DocIdSlideshowRouteImport } from './routes/doc.$id.slideshow'
import { Route as DocIdPreviewRouteImport } from './routes/doc.$id.preview'
import { Route as SpacesSpaceIdDocIdIndexRouteImport } from './routes/spaces.$spaceId.doc.$id.index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIndexRoute = LocalIndexRouteImport.update({
  id: '/local/',
  path: '/local/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorSlugRoute = TutorSlugRouteImport.update({
  id: '/tutor/$slug',
  path: '/tutor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalPreviewRoute = LocalPreviewRouteImport.update({
  id: '/local/preview',
  path: '/local/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdIndexRoute = SpacesSpaceIdIndexRouteImport.update({
  id: '/spaces/$spaceId/',
  path: '/spaces/$spaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdIndexRoute = DocIdIndexRouteImport.update({
  id: '/doc/$id/',
  path: '/doc/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdSettingsRoute = SpacesSpaceIdSettingsRouteImport.update({
  id: '/spaces/$spaceId/settings',
  path: '/spaces/$spaceId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdTimemachineRoute = DocIdTimemachineRouteImport.update({
  id: '/doc/$id/timemachine',
  path: '/doc/$id/timemachine',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdTeleprompterRoute = DocIdTeleprompterRouteImport.update({
  id: '/doc/$id/teleprompter',
  path: '/doc/$id/teleprompter',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdSlideshowRoute = DocIdSlideshowRouteImport.update({
  id: '/doc/$id/slideshow',
  path: '/doc/$id/slideshow',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdPreviewRoute = DocIdPreviewRouteImport.update({
  id: '/doc/$id/preview',
  path: '/doc/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdDocIdIndexRoute = SpacesSpaceIdDocIdIndexRouteImport.update({
  id: '/spaces/$spaceId/doc/$id/',
  path: '/spaces/$spaceId/doc/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/invite': typeof InviteRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/local/preview': typeof LocalPreviewRoute
  '/tutor/$slug': typeof TutorSlugRoute
  '/local/': typeof LocalIndexRoute
  '/doc/$id/preview': typeof DocIdPreviewRoute
  '/doc/$id/slideshow': typeof DocIdSlideshowRoute
  '/doc/$id/teleprompter': typeof DocIdTeleprompterRoute
  '/doc/$id/timemachine': typeof DocIdTimemachineRoute
  '/spaces/$spaceId/settings': typeof SpacesSpaceIdSettingsRoute
  '/doc/$id/': typeof DocIdIndexRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/doc/$id/': typeof SpacesSpaceIdDocIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/invite': typeof InviteRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/local/preview': typeof LocalPreviewRoute
  '/tutor/$slug': typeof TutorSlugRoute
  '/local': typeof LocalIndexRoute
  '/doc/$id/preview': typeof DocIdPreviewRoute
  '/doc/$id/slideshow': typeof DocIdSlideshowRoute
  '/doc/$id/teleprompter': typeof DocIdTeleprompterRoute
  '/doc/$id/timemachine': typeof DocIdTimemachineRoute
  '/spaces/$spaceId/settings': typeof SpacesSpaceIdSettingsRoute
  '/doc/$id': typeof DocIdIndexRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/doc/$id': typeof SpacesSpaceIdDocIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/invite': typeof InviteRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/local/preview': typeof LocalPreviewRoute
  '/tutor/$slug': typeof TutorSlugRoute
  '/local/': typeof LocalIndexRoute
  '/doc/$id/preview': typeof DocIdPreviewRoute
  '/doc/$id/slideshow': typeof DocIdSlideshowRoute
  '/doc/$id/teleprompter': typeof DocIdTeleprompterRoute
  '/doc/$id/timemachine': typeof DocIdTimemachineRoute
  '/spaces/$spaceId/settings': typeof SpacesSpaceIdSettingsRoute
  '/doc/$id/': typeof DocIdIndexRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/doc/$id/': typeof SpacesSpaceIdDocIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprint'
    | '/invite'
    | '/new'
    | '/privacy'
    | '/settings'
    | '/welcome'
    | '/local/preview'
    | '/tutor/$slug'
    | '/local/'
    | '/doc/$id/preview'
    | '/doc/$id/slideshow'
    | '/doc/$id/teleprompter'
    | '/doc/$id/timemachine'
    | '/spaces/$spaceId/settings'
    | '/doc/$id/'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/doc/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/invite'
    | '/new'
    | '/privacy'
    | '/settings'
    | '/welcome'
    | '/local/preview'
    | '/tutor/$slug'
    | '/local'
    | '/doc/$id/preview'
    | '/doc/$id/slideshow'
    | '/doc/$id/teleprompter'
    | '/doc/$id/timemachine'
    | '/spaces/$spaceId/settings'
    | '/doc/$id'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/doc/$id'
  id:
    | '__root__'
    | '/'
    | '/imprint'
    | '/invite'
    | '/new'
    | '/privacy'
    | '/settings'
    | '/welcome'
    | '/local/preview'
    | '/tutor/$slug'
    | '/local/'
    | '/doc/$id/preview'
    | '/doc/$id/slideshow'
    | '/doc/$id/teleprompter'
    | '/doc/$id/timemachine'
    | '/spaces/$spaceId/settings'
    | '/doc/$id/'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/doc/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprintRoute: typeof ImprintRoute
  InviteRoute: typeof InviteRoute
  NewRoute: typeof NewRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  LocalPreviewRoute: typeof LocalPreviewRoute
  TutorSlugRoute: typeof TutorSlugRoute
  LocalIndexRoute: typeof LocalIndexRoute
  DocIdPreviewRoute: typeof DocIdPreviewRoute
  DocIdSlideshowRoute: typeof DocIdSlideshowRoute
  DocIdTeleprompterRoute: typeof DocIdTeleprompterRoute
  DocIdTimemachineRoute: typeof DocIdTimemachineRoute
  SpacesSpaceIdSettingsRoute: typeof SpacesSpaceIdSettingsRoute
  DocIdIndexRoute: typeof DocIdIndexRoute
  SpacesSpaceIdIndexRoute: typeof SpacesSpaceIdIndexRoute
  SpacesSpaceIdDocIdIndexRoute: typeof SpacesSpaceIdDocIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/': {
      id: '/local/'
      path: '/local'
      fullPath: '/local/'
      preLoaderRoute: typeof LocalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/$slug': {
      id: '/tutor/$slug'
      path: '/tutor/$slug'
      fullPath: '/tutor/$slug'
      preLoaderRoute: typeof TutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/preview': {
      id: '/local/preview'
      path: '/local/preview'
      fullPath: '/local/preview'
      preLoaderRoute: typeof LocalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/': {
      id: '/spaces/$spaceId/'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof SpacesSpaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id/': {
      id: '/doc/$id/'
      path: '/doc/$id'
      fullPath: '/doc/$id/'
      preLoaderRoute: typeof DocIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/settings': {
      id: '/spaces/$spaceId/settings'
      path: '/spaces/$spaceId/settings'
      fullPath: '/spaces/$spaceId/settings'
      preLoaderRoute: typeof SpacesSpaceIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id/timemachine': {
      id: '/doc/$id/timemachine'
      path: '/doc/$id/timemachine'
      fullPath: '/doc/$id/timemachine'
      preLoaderRoute: typeof DocIdTimemachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id/teleprompter': {
      id: '/doc/$id/teleprompter'
      path: '/doc/$id/teleprompter'
      fullPath: '/doc/$id/teleprompter'
      preLoaderRoute: typeof DocIdTeleprompterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id/slideshow': {
      id: '/doc/$id/slideshow'
      path: '/doc/$id/slideshow'
      fullPath: '/doc/$id/slideshow'
      preLoaderRoute: typeof DocIdSlideshowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id/preview': {
      id: '/doc/$id/preview'
      path: '/doc/$id/preview'
      fullPath: '/doc/$id/preview'
      preLoaderRoute: typeof DocIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/doc/$id/': {
      id: '/spaces/$spaceId/doc/$id/'
      path: '/spaces/$spaceId/doc/$id'
      fullPath: '/spaces/$spaceId/doc/$id/'
      preLoaderRoute: typeof SpacesSpaceIdDocIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprintRoute: ImprintRoute,
  InviteRoute: InviteRoute,
  NewRoute: NewRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  LocalPreviewRoute: LocalPreviewRoute,
  TutorSlugRoute: TutorSlugRoute,
  LocalIndexRoute: LocalIndexRoute,
  DocIdPreviewRoute: DocIdPreviewRoute,
  DocIdSlideshowRoute: DocIdSlideshowRoute,
  DocIdTeleprompterRoute: DocIdTeleprompterRoute,
  DocIdTimemachineRoute: DocIdTimemachineRoute,
  SpacesSpaceIdSettingsRoute: SpacesSpaceIdSettingsRoute,
  DocIdIndexRoute: DocIdIndexRoute,
  SpacesSpaceIdIndexRoute: SpacesSpaceIdIndexRoute,
  SpacesSpaceIdDocIdIndexRoute: SpacesSpaceIdDocIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
